services:
    postgres:
        image: postgres:15
        container_name: contractflow-db
        restart: always
        environment:
          POSTGRES_USER: contractflow
          POSTGRES_PASSWORD: contractflow
          POSTGRES_DB: contractflow
        volumes:
          - pg_data:/var/lib/postgresql/data
        ports:
          - "5433:5432" 
volumes:
  pg_data:  